import Head from 'next/head';
import Content from '../src/components/content';
import Layout from '../src/components/layout';
import Header from '../src/components/header';
import Hero from '../src/components/content/hero';
import About from '../src/components/content/about';
import Footer from '../src/components/footer';
import Technologies from '../src/components/content/technologies';
import Steps from '../src/components/content/steps';
import Review from '../src/components/content/review';
import Questions from '../src/components/content/questions';
import Gallery from '../src/components/content/gallery';
import Contact from '../src/components/content/contact';
import { Provider } from 'react-redux';
import { store } from '../src/store';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Provider store={store}>
        <Layout>
          <Header />
          <Content>
            <Hero />
            <About />
            <Technologies />
            <Steps />
            <Questions />
            <Review />
            <Gallery />
            <Contact />
          </Content>
          <Footer />
        </Layout>
      </Provider>
    </>
  );
}
